version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run: node --version
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v1-dependencies-{{checksum "package.json"}}
            # find the most recently generated cache used from any branch
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm instal

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}

      # run test!
      - run:
          name: Run Tests
          command: npm run test

      - run:
          name: Run Build
          command: npm run build

      - run:
          name: Deploy at Netlify
          command: npm run deploy

workflows:
  build_deploy:
    jobs:
        - deploy
